// frontend/src/components/DatasetList.svelte
<script>
  import { fetchDatasets } from '../lib/api.js';

  let { onselect } = $props();

  let datasets = $state([]);
  let loading = $state(true);
  let error = $state(null);

  async function load() {
    loading = true;
    error = null;
    try {
      const res = await fetchDatasets();
      datasets = res.datasets;
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    load();
  });
</script>

<section>
  {#if loading}
    <p class="status">loading datasets...</p>
  {:else if error}
    <div class="error">
      <p>{error}</p>
      <button onclick={load}>retry</button>
    </div>
  {:else if datasets.length === 0}
    <p class="status">no datasets found</p>
  {:else}
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th>version</th>
          <th>data</th>
        </tr>
      </thead>
      <tbody>
        {#each datasets as dataset}
          <tr onclick={() => onselect(dataset)}>
            <td class="name">{dataset.name}</td>
            <td class="version">{dataset.version}</td>
            <td>
              <span class="dot" class:has-data={dataset.has_data}></span>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</section>

<style>
  section {
    width: 100%;
  }

  .status {
    color: var(--color-text-muted);
    padding: var(--space-lg) 0;
  }

  .error {
    color: var(--color-error);
    display: flex;
    align-items: center;
    gap: var(--space-md);
    padding: var(--space-lg) 0;
  }

  .error button {
    background: var(--color-surface);
    color: var(--color-text);
    border: 1px solid var(--color-border);
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-sm);
    cursor: pointer;
    font-size: 0.85rem;
  }

  .error button:hover {
    background: var(--color-surface-hover);
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  thead th {
    text-align: left;
    color: var(--color-text-muted);
    font-size: 0.75rem;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: var(--space-sm) var(--space-md);
    border-bottom: 1px solid var(--color-border);
  }

  tbody tr {
    cursor: pointer;
    transition: background 0.1s;
  }

  tbody tr:hover {
    background: var(--color-surface-hover);
  }

  tbody td {
    padding: var(--space-sm) var(--space-md);
    border-bottom: 1px solid var(--color-border);
  }

  .name {
    font-weight: 500;
  }

  .version {
    font-family: var(--font-mono);
    font-size: 0.85rem;
    color: var(--color-text-muted);
  }

  .dot {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--color-border);
  }

  .dot.has-data {
    background: var(--color-success);
  }
</style>

// frontend/src/components/dataset-list.tsx
import type { DatasetSummary } from "@/lib/api";

import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useDatasets } from "@/hooks/use-datasets";
import { cn } from "@/lib/utils";

interface DatasetListProps {
  onSelect: (dataset: DatasetSummary) => void;
}

/** landing page: all registered datasets with a dot marking which have data */
export function DatasetList({ onSelect }: DatasetListProps) {
  const { data: datasets, isPending, isError, error, refetch } = useDatasets();

  if (isPending) {
    return (
      <p className="text-muted-foreground py-8 text-sm">loading datasets...</p>
    );
  }

  if (isError) {
    return (
      <div className="border-destructive/50 space-y-3 rounded-md border p-4">
        <p className="text-destructive text-sm">{error.message}</p>
        <Button variant="outline" size="sm" onClick={() => refetch()}>
          retry
        </Button>
      </div>
    );
  }

  if (datasets.length === 0) {
    return (
      <p className="text-muted-foreground py-8 text-sm">no datasets found</p>
    );
  }

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>name</TableHead>
            <TableHead>version</TableHead>
            <TableHead>data</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {datasets.map((dataset) => (
            <TableRow
              key={`${dataset.name}@${dataset.version}`}
              className="cursor-pointer"
              onClick={() => onSelect(dataset)}
            >
              <TableCell>{dataset.name}</TableCell>
              <TableCell className="text-muted-foreground font-mono">
                {dataset.version}
              </TableCell>
              <TableCell>
                <span
                  className={cn(
                    "inline-block size-2 rounded-full",
                    dataset.has_data ? "bg-success" : "bg-border",
                  )}
                  title={dataset.has_data ? "has data" : "no data"}
                />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
