// frontend/src/components/dataset-detail.tsx
import { ArrowLeftIcon } from "lucide-react";
import { useMemo, useState } from "react";

import { DataTable } from "@/components/data-table";
import { JsonModal } from "@/components/json-modal";
import { Button } from "@/components/ui/button";
import { useDatasetData } from "@/hooks/use-dataset-data";
import { defaultDateRange } from "@/lib/format";

const PAGE_SIZE = 50;

interface DatasetDetailProps {
  name: string;
  version: string;
  onBack: () => void;
}

/** detail view: paginated data table over a 5-year window, newest first */
export function DatasetDetail({ name, version, onBack }: DatasetDetailProps) {
  // freeze the range for the lifetime of the view so the query key is stable
  const [range] = useState(() => defaultDateRange());
  const [page, setPage] = useState(0);
  const [selectedRow, setSelectedRow] = useState<Record<
    string,
    unknown
  > | null>(null);

  const { data, isPending, isError, error, refetch } = useDatasetData(
    name,
    version,
    range.start,
    range.end,
  );

  // newest first
  const allRows = useMemo(() => (data ? [...data.rows].reverse() : []), [data]);
  const totalPages = Math.max(1, Math.ceil(allRows.length / PAGE_SIZE));
  const pageRows = allRows.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  return (
    <div className="space-y-4">
      <Button
        variant="ghost"
        size="sm"
        onClick={onBack}
        className="text-muted-foreground -ml-2"
      >
        <ArrowLeftIcon /> back
      </Button>
      <h2 className="text-xl font-semibold">
        {name}{" "}
        <span className="text-muted-foreground font-mono text-base font-normal">
          {version}
        </span>
      </h2>

      {isPending && (
        <p className="text-muted-foreground py-8 text-sm">loading data...</p>
      )}

      {isError && (
        <div className="border-destructive/50 space-y-3 rounded-md border p-4">
          <p className="text-destructive text-sm">{error.message}</p>
          <Button variant="outline" size="sm" onClick={() => refetch()}>
            retry
          </Button>
        </div>
      )}

      {data && (
        <>
          <p className="text-muted-foreground text-sm">
            {data.returned_timestamps} timestamps · page {page + 1} of{" "}
            {totalPages}
          </p>
          <DataTable rows={pageRows} onRowClick={setSelectedRow} />
          {totalPages > 1 && (
            <div className="flex items-center gap-3">
              <Button
                variant="outline"
                size="sm"
                disabled={page === 0}
                onClick={() => setPage((p) => p - 1)}
              >
                ← newer
              </Button>
              <span className="text-muted-foreground text-sm">
                page {page + 1} / {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= totalPages - 1}
                onClick={() => setPage((p) => p + 1)}
              >
                older →
              </Button>
            </div>
          )}
        </>
      )}

      <JsonModal data={selectedRow} onClose={() => setSelectedRow(null)} />
    </div>
  );
}

// frontend/src/components/DatasetDetail.svelte
<script>
  import { fetchData } from '../lib/api.js';
  import { defaultDateRange } from '../lib/format.js';
  import DataTable from './DataTable.svelte';
  import JsonModal from './JsonModal.svelte';

  const PAGE_SIZE = 50;

  let { name, version, onback } = $props();

  let result = $state(null);
  let loading = $state(false);
  let error = $state(null);
  let modalRow = $state(null);
  let page = $state(0);

  // newest data first
  let allRows = $derived(result?.rows ? [...result.rows].reverse() : []);
  let totalPages = $derived(Math.max(1, Math.ceil(allRows.length / PAGE_SIZE)));
  let pageRows = $derived(allRows.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE));

  async function load() {
    loading = true;
    error = null;
    try {
      const { start, end } = defaultDateRange();
      result = await fetchData(name, version, start, end);
      page = 0;
    } catch (e) {
      error = e.message;
      result = null;
    } finally {
      loading = false;
    }
  }

  // auto-fetch on mount
  $effect(() => {
    load();
  });

  function handleRowClick(rowData) {
    modalRow = rowData;
  }
</script>

<div class="detail">
  <button class="back" onclick={onback}>&larr; back</button>

  <h2>{name} <span class="ver">{version}</span></h2>

  {#if loading}
    <p class="status">loading...</p>
  {:else if error}
    <div class="error">
      <p>{error}</p>
      <button onclick={load}>retry</button>
    </div>
  {:else if result}
    <p class="meta">
      {result.returned_timestamps} timestamps &middot; page {page + 1} of {totalPages}
    </p>

    <DataTable rows={pageRows} onrowclick={handleRowClick} />

    {#if totalPages > 1}
      <div class="pagination">
        <button onclick={() => (page = page - 1)} disabled={page === 0}>
          &larr; newer
        </button>
        <span class="page-info">page {page + 1} / {totalPages}</span>
        <button onclick={() => (page = page + 1)} disabled={page >= totalPages - 1}>
          older &rarr;
        </button>
      </div>
    {/if}
  {/if}

  {#if modalRow}
    <JsonModal data={modalRow} onclose={() => (modalRow = null)} />
  {/if}
</div>

<style>
  .detail {
    width: 100%;
  }

  .back {
    background: none;
    border: none;
    color: var(--color-accent);
    cursor: pointer;
    font-size: 0.875rem;
    padding: 0;
    margin-bottom: var(--space-md);
  }

  .back:hover {
    color: var(--color-accent-hover);
  }

  h2 {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: var(--space-lg);
  }

  .ver {
    font-family: var(--font-mono);
    font-size: 0.85rem;
    color: var(--color-text-muted);
    font-weight: 400;
  }

  .status {
    color: var(--color-text-muted);
    padding: var(--space-lg) 0;
  }

  .error {
    color: var(--color-error);
    display: flex;
    align-items: center;
    gap: var(--space-md);
    margin-bottom: var(--space-md);
  }

  .error button {
    background: var(--color-surface);
    color: var(--color-text);
    border: 1px solid var(--color-border);
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-sm);
    cursor: pointer;
    font-size: 0.85rem;
  }

  .error button:hover {
    background: var(--color-surface-hover);
  }

  .meta {
    font-size: 0.8rem;
    color: var(--color-text-muted);
    margin-bottom: var(--space-md);
  }

  .pagination {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: var(--space-lg);
    padding: var(--space-lg) 0;
  }

  .pagination button {
    background: var(--color-surface);
    color: var(--color-text);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    padding: var(--space-xs) var(--space-md);
    font-size: 0.85rem;
    cursor: pointer;
  }

  .pagination button:hover:not(:disabled) {
    background: var(--color-surface-hover);
  }

  .pagination button:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .page-info {
    font-size: 0.8rem;
    color: var(--color-text-muted);
    font-family: var(--font-mono);
  }
</style>
