// frontend/src/components/data-table.tsx
import type { DataRow } from "@/lib/api";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface DataTableProps {
  rows: DataRow[];
  onRowClick: (payload: Record<string, unknown>) => void;
}

function formatCell(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

/**
 * renders dataset rows with columns derived from the first entry's keys.
 * timestamps with multiple entries (e.g. one per ticker) render one <tr> per
 * entry with the timestamp cell rowspanned across them.
 */
export function DataTable({ rows, onRowClick }: DataTableProps) {
  const firstEntry = rows.find((row) => row.data.length > 0)?.data[0];

  if (rows.length === 0 || firstEntry === undefined) {
    return (
      <p className="text-muted-foreground py-8 text-center text-sm">
        no data for this range
      </p>
    );
  }

  const columns = Object.keys(firstEntry);

  return (
    <div className="overflow-x-auto rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="font-mono">timestamp</TableHead>
            {columns.map((col) => (
              <TableHead key={col} className="font-mono">
                {col}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.flatMap((row) =>
            row.data.map((entry, i) => (
              <TableRow
                key={`${row.timestamp}-${i}`}
                className="cursor-pointer"
                onClick={() =>
                  onRowClick({ timestamp: row.timestamp, ...entry })
                }
              >
                {i === 0 && (
                  <TableCell
                    rowSpan={row.data.length}
                    className="text-muted-foreground align-top font-mono"
                  >
                    {row.timestamp}
                  </TableCell>
                )}
                {columns.map((col) => (
                  <TableCell key={col} className="font-mono">
                    {formatCell(entry[col])}
                  </TableCell>
                ))}
              </TableRow>
            )),
          )}
        </TableBody>
      </Table>
    </div>
  );
}

// frontend/src/components/DataTable.svelte
<script>
  let { rows, onrowclick } = $props();

  // derive column headers from keys of the first data entry
  let columns = $derived(() => {
    if (!rows || rows.length === 0) return [];
    for (const row of rows) {
      if (row.data && row.data.length > 0) {
        return Object.keys(row.data[0]);
      }
    }
    return [];
  });
</script>

{#if !rows || rows.length === 0}
  <p class="empty">no data for this range</p>
{:else}
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>timestamp</th>
          {#each columns() as col}
            <th>{col}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each rows as row}
          {#each row.data as entry, i}
            <tr onclick={() => onrowclick({ timestamp: row.timestamp, ...entry })}>
              {#if i === 0}
                <td class="ts" rowspan={row.data.length}>{row.timestamp}</td>
              {/if}
              {#each columns() as col}
                <td>{entry[col] ?? ''}</td>
              {/each}
            </tr>
          {/each}
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<style>
  .empty {
    color: var(--color-text-muted);
    padding: var(--space-lg) 0;
  }

  .table-wrap {
    overflow-x: auto;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }

  thead th {
    text-align: left;
    color: var(--color-text-muted);
    font-size: 0.75rem;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: var(--space-sm) var(--space-md);
    border-bottom: 1px solid var(--color-border);
    white-space: nowrap;
  }

  tbody tr {
    cursor: pointer;
    transition: background 0.1s;
  }

  tbody tr:hover {
    background: var(--color-surface-hover);
  }

  tbody td {
    padding: var(--space-sm) var(--space-md);
    border-bottom: 1px solid var(--color-border);
    white-space: nowrap;
  }

  .ts {
    font-family: var(--font-mono);
    font-size: 0.8rem;
    color: var(--color-text-muted);
    vertical-align: top;
  }
</style>
