// frontend/src/App.svelte
<script>
  import DatasetList from './components/DatasetList.svelte';
  import DatasetDetail from './components/DatasetDetail.svelte';

  // view state: 'list' or 'detail'
  let view = $state('list');
  let selectedDataset = $state(null);

  function handleSelect(dataset) {
    selectedDataset = dataset;
    view = 'detail';
  }

  function handleBack() {
    selectedDataset = null;
    view = 'list';
  }
</script>

<header>
  <h1>Datastream</h1>
</header>

<main>
  {#if view === 'list'}
    <DatasetList onselect={handleSelect} />
  {:else if view === 'detail' && selectedDataset}
    <DatasetDetail
      name={selectedDataset.name}
      version={selectedDataset.version}
      onback={handleBack}
    />
  {/if}
</main>

<style>
  header {
    margin-bottom: var(--space-xl);
  }

  h1 {
    font-size: 1.5rem;
    font-weight: 600;
    letter-spacing: -0.02em;
  }
</style>

// frontend/src/App.tsx
import { KeyRoundIcon } from "lucide-react";
import { useState } from "react";

import type { DatasetSummary } from "@/lib/api";

import { ApiKeyDialog } from "@/components/api-key-dialog";
import { DatasetDetail } from "@/components/dataset-detail";
import { DatasetList } from "@/components/dataset-list";
import { Button } from "@/components/ui/button";
import { useApiKey } from "@/hooks/use-api-key";

type View = { view: "list" } | { view: "detail"; dataset: DatasetSummary };

function App() {
  const { setDialogOpen } = useApiKey();
  const [view, setView] = useState<View>({ view: "list" });

  return (
    <div className="mx-auto max-w-[1200px] px-8 py-6">
      <header className="mb-8 flex items-center justify-between">
        <h1 className="text-2xl font-semibold">Datastream</h1>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setDialogOpen(true)}
          className="text-muted-foreground"
        >
          <KeyRoundIcon /> API key
        </Button>
      </header>
      <main>
        {view.view === "list" ? (
          <DatasetList
            onSelect={(dataset) => setView({ view: "detail", dataset })}
          />
        ) : (
          <DatasetDetail
            name={view.dataset.name}
            version={view.dataset.version}
            onBack={() => setView({ view: "list" })}
          />
        )}
      </main>
      <ApiKeyDialog />
    </div>
  );
}

export default App;
